openapi: 3.0.0
info:
  title: Dart Scorekeeper
  version: 1.0.0
paths:
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: http
        url: http://10.77.0.10:3000/
        headers:
          '*': '*'
        query:
          '*': '*'
        timeouts:
          connect: 2
          read: 15
  /{path+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: http
        url: http://10.77.0.10:3000/{path}
        headers:
          '*': '*'
        query:
          '*': '*'
        timeouts:
          connect: 2
          read: 15
      parameters:
        - name: path
          in: path
          required: false
          schema:
            type: string
